services:
  - type: web
    name: rescue-backend
    runtime: python3
    buildCommand: pip install --no-cache-dir -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: "3.11"
      - key: PIP_ONLY_BINARY
        value: ":all:"
